#
# Copyright (c) 2026-present Godot Mobile Plugins (https://github.com/godot-mobile-plugins)
#
extends: default
rules:
  line-length: 120
  document-start: disable
  comments:
    min-spaces-from-content: 3
    require-starting-space: true
  empty-lines:
    max: 1
