#
# © 2026-present https://github.com/<<GitHubUsername>>
#

gradleProjectName=godot-plugin-template-plugin

# Set plugin-specific extra properties common for all modules
#extra.myProperty=value

# Configure plugin-specific Gradle scripts common for all modules
#gradle.extraGradle=extra.gradle.kts
