#
# © 2026-present https://github.com/<<GitHubUsername>>
#

# Set plugin-specific extra properties for android module
#extra.myProperty=value

# Configure plugin-specific Gradle scripts for android module
#gradle.extraGradle=extra.gradle.kts
